roses_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^skills/', include('skills.urls', namespace='skills')),
)

skills/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from skills import views

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='skills/index.html'), name='index'),
    #
    url(r'^roles/$', views.RolesList.as_view(), name='roles'),
    url(r'^role/add/$', views.RoleCreate.as_view(), name='role_add'),
    url(r'^role/(?P<pk>\d+)/$', views.RoleUpdate.as_view(), name='role_update'),
    url(r'^role/(?P<pk>\d+)/delete/$', views.RoleDelete.as_view(), name='role_delete'),
    #
    url(r'^seniority/add/$', views.SeniorityCreate.as_view(), name='seniority_add'),
    url(r'^seniority/(?P<pk>\d+)/$', views.SeniorityUpdate.as_view(), name='seniority_update'),
    url(r'^seniority/(?P<pk>\d+)/delete/$', views.SeniorityDelete.as_view(), name='seniority_delete'),
    #
    url(r'^skills/$', views.SkillsList.as_view(), name='skills'),
    url(r'^skill/add/$', views.SkillCreate.as_view(), name='skill_add'),
    url(r'^skill/(?P<pk>\d+)/$', views.SkillUpdate.as_view(), name='skill_update'),
    url(r'^skill/(?P<pk>\d+)/delete/$', views.SkillDelete.as_view(), name='skill_delete'),
)

skills/models.py
from django.db import models
from django.core.urlresolvers import reverse


NAME_MAX_LEN = 256
SKILL_NAME_MAX_LEN = 1024


class Role(models.Model):
    name = models.CharField(max_length=NAME_MAX_LEN)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('skills:roles')


class Seniority(models.Model):
    name = models.CharField(max_length=NAME_MAX_LEN)
    rank = models.PositiveSmallIntegerField()
    role = models.ForeignKey('skills.Role', related_name='seniorities')

    def __str__(self):
        return '{self.role} - {self.name}'.format(self=self)

    def get_absolute_url(self):
        return reverse('skills:seniority_update', kwargs={'pk': self.pk})

class Skill(models.Model):
    name = models.CharField(max_length=SKILL_NAME_MAX_LEN)
    seniority = models.ManyToManyField('skills.Seniority',
                                       through='skills.SenioritySkills',
                                       related_name='skills')

    def __str__(self):
        return self.name

    def related_seniorities(self):
        # For the admin
        return ['{ss.seniority}: {ss.level}'.format(ss=ss)
                for ss in self.seniority_levels.all()]
    #related_seniorities.short_description = 'Related seniorities'

class SenioritySkills(models.Model):
    NONE = 'none'
    LOW = 'low'
    MID = 'mid'
    HIGH = 'high'
    EXPERT = 'expert'
    LEVEL_CHOICES = (
        (NONE, 'None'),
        (LOW, 'Low'),
        (MID, 'Medium'),
        (HIGH, 'High'),
        (EXPERT, 'Expert'),
    )
    seniority = models.ForeignKey('skills.Seniority',
                                  related_name='skill_levels')
    skill = models.ForeignKey('skills.Skill',
                              related_name='seniority_levels')
    level = models.CharField(choices=LEVEL_CHOICES, max_length=NAME_MAX_LEN)

    def __str__(self):
        return '{ss.seniority} -- {ss.skill}: {ss.level}'.format(ss=self)

skills/views.py
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.views.generic.list import MultipleObjectMixin

from skills.models import Role, Seniority, Skill


class RolesList(generic.ListView):
    model = Role
    fields = ['name', 'description']
    template_name = 'skills/role_list.html'


class RoleCreate(generic.CreateView):
    model = Role
    fields = ['name', 'description']


class RoleUpdate(generic.UpdateView, MultipleObjectMixin):
    model = Role
    fields = ['name', 'description']
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Role.objects.all())
        self.object_list = self.object.seniorities.all()
        return super(RoleUpdate, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(RoleUpdate, self).get_context_data(**kwargs)
        context['role'] = self.object
        return context


class RoleDelete(generic.DeleteView):
    model = Role
    success_url = reverse_lazy('skills:roles')
    template_name = 'skills/confirm_delete.html'


#
# Seniorities
#
class SeniorityCreate(generic.CreateView):
    model = Seniority
    fields = ['name', 'rank', 'role']


class SeniorityUpdate(generic.UpdateView, MultipleObjectMixin):
    model = Seniority
    fields = ['name', 'rank', 'role']
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Seniority.objects.all())
        self.object_list = self.object.skills.all()
        return super(SeniorityUpdate, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SeniorityUpdate, self).get_context_data(**kwargs)
        context['seniority'] = self.object
        return context


class SeniorityDelete(generic.DeleteView):
    model = Seniority
    success_url = reverse_lazy('skills:roles')
    template_name = 'skills/confirm_delete.html'


#
# SKills
#

class SkillsList(generic.ListView):
    model = Skill
    fields = ['name']

class SkillCreate(generic.CreateView):
    model = Skill
    fields = ['name']
    success_url = reverse_lazy('skills:skills')


class SkillUpdate(generic.UpdateView):
    model = Skill
    fields = ['name']
    success_url = reverse_lazy('skills:skills')


class SkillDelete(generic.DeleteView):
    model = Skill
    success_url = reverse_lazy('skills:roles')
    template_name = 'skills/confirm_delete.html'

skills/templates/skills/base.html
{% load staticfiles %}

<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SKIMO | Welcome</title>
    <link rel="stylesheet" href="{% static 'skills/css/foundation.min.css' %}" />
    <link rel="stylesheet" href="{% static 'skills/css/skills.css' %}" />
    {% block css %}
    {% endblock %}
    <script src="{% static 'skills/js/vendor/modernizr.js' %}"></script>
  </head>
  <body>

    <nav class="top-bar foundation-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
         <span data-tooltip class="has-tip" title="Try resizing your browser to see how the grid stacks"><h1 class="show-for-small-only"><a href="#">Small screen</a></h1></span>
         <span data-tooltip class="has-tip" title="Try resizing your browser to see how the grid stacks"><h1 class="show-for-medium-only"><a href="#">Medium Screen</a></h1></span>
         <span data-tooltip class="has-tip" title="Try resizing your browser to see how the grid stacks"><h1 class="show-for-large-only"><a href="#">Large screen</a></h1></span>
        </li>
      </ul>
      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li><a  href="{% url 'skills:skills' %}">Skills</a></li>
          <li><a  href="{% url 'skills:roles' %}">Roles</a></li>
          <li><a  href="{% url 'skills:index' %}">Home</a></li>
        </ul>
      </section>
    </nav>

    {% block main_contents %}
    {% endblock %}

    <script src="{% static 'skills/js/vendor/jquery.js' %}"></script>
    <script src="{% static 'skills/js/foundation.min.js' %}"></script>
    <script src="{% static 'skills/js/foundation/foundation.topbar.js' %}"></script>
    <script>
      $(document).foundation();
    </script>
    {% block end_js %}
    {% endblock %}
  </body>
</html>

skills/templates/skills/confirm_delete.html
{% extends "skills/base.html" %}
{% block main_contents %}
<div class="row">
    <div class="small-6 small-centered columns">
        <h1>Delete</h1>
    </div>
</div>

<div class="row">
    <div class="small-6 small-centered columns">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete <em>{{ object }}</em>?</p>
            <input type="submit" value="Confirm" class="button small alert"/>
            <input type="button" value="Cancel" class="button small" onClick="history.go(-1);return true;" />
        </form>
    </div>
</div>
{% endblock %}

skills/templates/skills/index.html
{% extends "skills/base.html" %}

{% block main_contents %}

<div class="row">
  <div class="large-12 columns">
    <h1>Welcome to the Skills Management Tool</h1>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <div class="panel">
        <h3>We&rsquo;re stoked you want to try it! </h3>
        <p>To get going, this file (index.html) includes some basic styles you can modify, play around with, or totally destroy to get going.</p>
        <p>Once you've exhausted the fun in this document, you should check out:</p>
        <div class="row">
            <div class="large-4 medium-4 columns">
                <p><a href="{% url 'skills:roles' %}">The Roles</a><br />Everything you need to know about defining new roles.</p>
            </div>
            <div class="large-4 medium-4 columns">
                <p><a href="">The Seniorities</a><br />...</p>
            </div>
            <div class="large-4 medium-4 columns">
                <p><a href="{% url 'skills:skills' %}">The Skills</a><br />alma matter of this tool.</p>
            </div>
        </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-8 medium-8 columns">
    <h5>Here&rsquo;s your basic grid:</h5>
    <!-- Grid Example -->

    <div class="row">
      <div class="large-12 columns">
        <div class="callout panel">
          <p><strong>This is a twelve column section in a row.</strong> Each of these includes a div.panel element so you can see where the columns are - it's not required at all for the grid.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="large-6 medium-6 columns">
        <div class="callout panel">
          <p>Six columns</p>
        </div>
      </div>
      <div class="large-6 medium-6 columns">
        <div class="callout panel">
          <p>Six columns</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="large-4 medium-4 small-4 columns">
        <div class="callout panel">
          <p>Four columns</p>
        </div>
      </div>
      <div class="large-4 medium-4 small-4 columns">
        <div class="callout panel">
          <p>Four columns</p>
        </div>
      </div>
      <div class="large-4 medium-4 small-4 columns">
        <div class="callout panel">
          <p>Four columns</p>
        </div>
      </div>
    </div>

    <hr />

    <h5>We bet you&rsquo;ll need a form somewhere:</h5>
    <form>
              <div class="row">
                <div class="large-12 columns">
                  <label>Input Label</label>
                  <input type="text" placeholder="large-12.columns" />
                </div>
              </div>
              <div class="row">
                <div class="large-4 medium-4 columns">
                  <label>Input Label</label>
                  <input type="text" placeholder="large-4.columns" />
                </div>
                <div class="large-4 medium-4 columns">
                  <label>Input Label</label>
                  <input type="text" placeholder="large-4.columns" />
                </div>
                <div class="large-4 medium-4 columns">
                  <div class="row collapse">
                    <label>Input Label</label>
                    <div class="small-9 columns">
                      <input type="text" placeholder="small-9.columns" />
                    </div>
                    <div class="small-3 columns">
                      <span class="postfix">.com</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="large-12 columns">
                  <label>Select Box</label>
                  <select>
                    <option value="husker">Husker</option>
                    <option value="starbuck">Starbuck</option>
                    <option value="hotdog">Hot Dog</option>
                    <option value="apollo">Apollo</option>
                  </select>
                </div>
              </div>
              <div class="row">
                <div class="large-6 medium-6 columns">
                  <label>Choose Your Favorite</label>
                  <input type="radio" name="pokemon" value="Red" id="pokemonRed"><label for="pokemonRed">Radio 1</label>
                  <input type="radio" name="pokemon" value="Blue" id="pokemonBlue"><label for="pokemonBlue">Radio 2</label>
                </div>
                <div class="large-6 medium-6 columns">
                  <label>Check these out</label>
                  <input id="checkbox1" type="checkbox"><label for="checkbox1">Checkbox 1</label>
                  <input id="checkbox2" type="checkbox"><label for="checkbox2">Checkbox 2</label>
                </div>
              </div>
              <div class="row">
                <div class="large-12 columns">
                  <label>Textarea Label</label>
                  <textarea placeholder="small-12.columns"></textarea>
                </div>
              </div>
            </form>
  </div>

  <div class="large-4 medium-4 columns">
          <h5>Try one of these buttons:</h5>
          <p><a href="#" class="small button">Simple Button</a><br/>
    <a href="#" class="small radius button">Radius Button</a><br/>
    <a href="#" class="small round button">Round Button</a><br/>
    <a href="#" class="medium success button">Success Btn</a><br/>
    <a href="#" class="medium alert button">Alert Btn</a><br/>
    <a href="#" class="medium secondary button">Secondary Btn</a></p>
            <div class="panel">
        <h5>So many components, girl!</h5>
        <p>A whole kitchen sink of goodies comes with Foundation. Checkout the docs to see them all, along with details on making them your own.</p>
        <a href="http://foundation.zurb.com/docs/" class="small button">Go to Foundation Docs</a>
    </div>
  </div>
</div>


{% endblock %}

skills/templates/skills/role_confirm_delete.html
{% extends "skills/base.html" %}
{% block main_contents %}
<div class="row">
    <div class="small-6 small-centered columns">
        <h1>Delete</h1>
    </div>
</div>

<div class="row">
    <div class="small-6 small-centered columns">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete <em>{{ object }}</em>?</p>
            <input type="submit" value="Confirm" class="button small alert"/>
            <input type="button" value="Cancel" class="button small" onClick="history.go(-1);return true;" />
        </form>
    </div>
</div>
{% endblock %}

skills/templates/skills/role_detail.html
{% extends "skills/base.html" %}
{% block main_contents %}

    <div class="row">
        <div class="small-12 columns">

            <h2>Role: {{ role.name }}</h2>

            <ol>
                {% for sen in page_obj %}
                    <li>{{ sen.name }}</li>
                {% endfor %}
            </ol>

            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>

        </div>
    </div>

{% endblock %}

skills/templates/skills/role_form.html
{% extends "skills/base.html" %}
{% block main_contents %}

{% include 'skills/snippets/save_form.html' with entity_name="Role" form=form %}

{% if role %}
    <div class="row">
        <div class="small-12 columns">
            <h1>Role seniorities</h1>
            <table>
              <tbody>
                {% for sen in page_obj %}
                <tr>
                    <td><a href="{% url 'skills:seniority_update' pk=sen.pk %}">{{ sen.name }}</td>
                    <td><a class="right" title="Delete" href="{% url 'skills:seniority_delete' pk=sen.pk %}">
                        <span class="round alert label">&times;</span></a>
                    </td>
                </tr>

                {% empty %}
                    <tr>No related seniorities.</tr>
                {% endfor %}
              </tbody>
            </table>
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
            <a href="{% url 'skills:seniority_add' %}" class="small button success">Add A Seniority</a>
        </div>
    </div>
{% endif %}

{% endblock %}

skills/templates/skills/role_list.html
{% extends "skills/base.html" %}
{% block main_contents %}

    <div class="row">
        <div class="small-12">

            <h1>Roles</h1>
            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Edit</th>
                  <th>Seniorities</th>
                  <th>&nbsp;</th>
                </tr>
              </thead>
              <tbody>
                {% for role in object_list %}
                <tr>
                    <td>{{ role.name }}</td>
                    <td>{{ role.description }}</td>
                    <td><a href="{% url 'skills:role_update' pk=role.pk %}">Edit</td>
                    <td>Skills</td>
                    <td><a class="right" title="Delete" href="{% url 'skills:role_delete' pk=role.pk %}"><span class="round alert label">X</span></a></td>
                </tr>

                {% empty %}
                    <li>No roles yet.</li>
                {% endfor %}
              </tbody>
            </table>

            <a href="{% url 'skills:role_add' %}" class="button">Add Role</a>

        </div>
    </div>

{% endblock %}

skills/templates/skills/seniority_form.html
{% extends "skills/base.html" %}
{% block main_contents %}

{% include 'skills/snippets/save_form.html' with entity_name="Seniority" form=form %}

<p> include list of related skills, with level.

{% endblock %}

skills/templates/skills/skill_form.html
{% extends "skills/base.html" %}
{% block main_contents %}

{% include 'skills/snippets/save_form.html' with entity_name="Skill" form=form %}

{% if skill %}
    <div class="row">
        <div class="small-12 columns">
           Show Roles/seniorities with this skill's level
        </div>
    </div>
{% endif %}

{% endblock %}

skills/templates/skills/skill_list.html
{% extends "skills/base.html" %}
{% block main_contents %}

    <div class="row">
        <div class="small-12">

            <h1>Skills</h1>
            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Edit</th>
                  <th>&nbsp;</th>
                </tr>
              </thead>
              <tbody>
                {% for skill in object_list %}
                <tr>
                    <td>{{ skill.name }}</td>
                    <td><a href="{% url 'skills:skill_update' pk=skill.pk %}">Edit</td>
                    <td>Skills</td>
                    <td><a class="right" title="Delete" href="{% url 'skills:skill_delete' pk=skill.pk %}"><span class="round alert label">&times;</span></a></td>
                </tr>

                {% empty %}
                    <tr><td colspan="3">No skills yet.</td></tr>
                {% endfor %}
              </tbody>
            </table>

            <a href="{% url 'skills:skill_add' %}" class="button">Add SKill</a>

        </div>
    </div>

{% endblock %}

skills/templates/skills/snippets/save_form.html
<div class="row">
    <div class="small-12 columns">
        <h1>{{ entity_name }} details</h1>
        <form action="" method="post">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {{ form.non_field_errors }}
            {% for field in form.visible_fields %}
                <div class="fieldWrapper">
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="button success">Save</button>
            <a type="cancel" class="button" onClick="history.go(-1);return true;">Cancel</a>
        </form>
    </div>
</div>